name: nodeStats
magi_version: 1.7
display: Node Statistics
description: An agent that collects general node information and CPU + load average statistics
execute: thread 
mainfile: nodeStats.py
inherits:
  - ReportingDispatchAgent
variables:
  - name: experimentDescription
    help: free form text describing the experiment and/or testrun
    type: string
  - name: nodeDescription
    help: free form text describing the node
    type: string
method: 
  - name: startCollection
    help: Start collecting stats about this node.
    args: { }
  - name: stopCollection
    help: Stop collecting stats
    args: { }

