name: fileCreator
display: File Creator Agent
description:  This agent creates a file on the test node.
execute: thread
mainfile: FileCreator.py
inherits:
   - DispatchAgent

methods:
   - name: createFile
     help: Create the file
     args: []

variables:
   - name: sourceFile
     help: the full path of the file to use to copy
     type: string

   - name: destinationFile
     help: the full path of the created file 
     type: string
