name: Link_up_down
display: Link up and down agent
description:  This agent can help you put links between nodes up and down
execute: socket 
mainfile: Link_up_down.py
inherits:
   - DispatchAgent 

methods:
   - name: link_up
     help: can put link up
     args: [link_name, timing] 
   - name: link_down
     help: can put link down
     args: [link_name, timing] 
